# Generated by Django 4.2.3 on 2023-07-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='media/tyson/F0563249563210B8/codes/Vs Code/Django/youtubeClone-django/youtubeClone_django/static/thumbnails/')),
                ('video_time', models.TimeField()),
                ('channel_picture', models.ImageField(upload_to='media/tyson/F0563249563210B8/codes/Vs Code/Django/youtubeClone-django/youtubeClone_django/static/channel-pictures/')),
                ('video_title', models.CharField(max_length=500)),
                ('video_author', models.CharField(max_length=100)),
                ('views', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=100)),
            ],
        ),
    ]
